site_name: Task Tree

plugins:
  - search
  - excalidraw

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - API: API.md
  - Logging: Logging.md
theme:
  name: material